apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  labels:
    app: service1
spec:
  replicas: 3           # Number of desired replicas (adjust as needed)
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: your-registry/service1:latest   # Replace with your Docker image
        ports:
        - containerPort: 8080                # Port your microservice listens on
---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Exposes the service externally (use LoadBalancer, NodePort, or ClusterIP as needed)
